name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: enriikke/gatsby-gh-pages-action@v2.1.1
      with:
        access-token: abc
        deploy-branch: gh-pages
